version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: my-mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-phpmyadmin-container
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "80:80"
    depends_on:
      - mariadb
