version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb-container
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    container_name: my-mongo-express-container
    ports:
      - "80:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb
