version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my-pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: my_email@example.com
      PGADMIN_DEFAULT_PASSWORD: my_pgadmin_password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "80:80"
    depends_on:
      - postgres
