version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis-container
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: my-redis-commander-container
    environment:
      REDIS_HOSTS: my-redis-container
    ports:
      - "80:8081"
    depends_on:
      - redis
